### PR TITLE
Update go-jsonnet to v0.18.0

### PR DESCRIPTION
**Pull request by julienduchesne**
This should add some new functions
See https://github.com/google/jsonnet/releases/tag/v0.18.0

### CODE REVIEW

**Review by jvrplmlmn — APPROVED** [review]
👍

**Comment by Duologic** [comment]
I think we need to discuss on whether we keep `parseYaml` or use upstream, no?

**Comment by julienduchesne** [comment]
> I think we need to discuss on whether we keep `parseYaml` or use upstream, no?

Hmm, yeah. Good point

**Comment by olegmayko** [comment]
It would be nice if you merge and cut release soon. Some std.functions are long expected. Thank you!

**Comment by julienduchesne** [comment]
> It would be nice if you merge and cut release soon. Some std.functions are long expected. Thank you!

👍 . I was aiming for a release next week

**Comment by julienduchesne** [comment]
We'll be leaving `std.native("parseYaml")` for now to not break compatibility

**Pull request merged**
