### PR TITLE
doc: Add note about environment name and pruning

### PR DESCRIPTION
**Pull request by remram44**
People using this feature should be aware of the gotchas.

See #824

### CODE REVIEW

**Comment by remram44** [comment]
Bump, what do you think?

**Comment by remram44** [comment]
Bump, this thing on?

**Comment by julienduchesne** [comment]
Closing in favour of https://github.com/grafana/tanka/pull/975

**Comment by remram44** [comment]
#975 still needs an update to the docs or defaults otherwise Tanka still destroys environments and eats data.

**Pull request closed without merging**
