### PR TITLE
Update resources.go to take output from kubectl@1.26

### PR DESCRIPTION
**Pull request by leizor**
Fixes https://github.com/grafana/tanka/issues/795.

### CODE REVIEW

**Review by colega — APPROVED** [review]
I built the binary and checked that it works for me with kubectl 1.26 and server 1.25.

**Comment by zalegrala** [comment]
May we have a release for this change?

**Comment by BenjaminPelletier** [comment]
#795 prevented a partner from using Tanka to deploy our software product today; I would appreciate a release for this change also.

**Comment by julienduchesne** [comment]
I will create a release early next week

**Comment by julienduchesne** [comment]
This is released in v0.24.0

**Pull request merged**
