### PR TITLE
Add Apple Silicon binary

### PR DESCRIPTION
**Pull request by BeyondEvil**
Adds support for Apple Silicon aka arm64.

### CODE REVIEW

**Comment by BeyondEvil** [comment]
I probably did an oopsie somehow: `Build is blocked, please, contact repo admin in order to proceed`

**Comment by BeyondEvil** [comment]
I think I've solved it @Duologic , but you need to approve the build.

Also, GitHub seems to be experiencing some issues.

**Comment by Duologic** [comment]
Looks like it worked!

**Comment by BeyondEvil** [comment]
> Looks like it worked!

Nice!

Is it possible to rerun the failed ones?

Are my changes sufficient to also actually publish the arm64 under the release?

**Comment by Duologic** [comment]
Hmm, now I'm thinking we should consider an Apple Silicon docker image too, but I don't know how that would work (it also has several other binaries that need to be taken into account.

**Comment by BeyondEvil** [comment]
> Hmm, now I'm thinking we should consider an Apple Silicon docker image too, but I don't know how that would work (it also has several other binaries that need to be taken into account.

Good point. 🤔

**Review by julienduchesne — APPROVED** [review]
LGTM! I've signed the Drone yaml file

**Comment by BeyondEvil** [comment]
Anything more I can do?

**Comment by Duologic** [comment]
We can do the docker image in a separate PR.

**Pull request merged**
