### PR TITLE
Propagate kubectl errors.

### PR DESCRIPTION
**Pull request by tomwilkie**
Part of #59

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by sh0rez** [comment]
Stderr was muted, because kubectl prints `exit status 1` on diff.

I would rather capture the output into a buffer and only print it if there is an error but which is not a diff

**Comment by tomwilkie** [comment]
Can do!  How do we detect if it is a valid diff?

**Comment by sh0rez** [comment]
I believe stderr contains a literal `exit status 1` and nothing else in that case. But verify that first please, not totally sure

**Comment by sh0rez** [comment]
As I really only care about not having the `exit status 1` on diff, we could also implement some kind of "`stderr`-middleware" that is written to and forwards everything but `exit status .*` to stderr

**Pull request closed without merging**
