### PR TITLE
add flag to allow insecure tls cert

### PR DESCRIPTION
**Pull request by ronandoolan2**
Allow flag for using kubectl with insecure tls configuration
`kubectl --insecure-skip-tls-verify`

### CODE REVIEW

**Comment by ronandoolan2** [comment]
@sh0rez @Duologic please review when you can.

**Comment by julienduchesne** [comment]
This can be set in the kubeconfig directly. Do you have a usecase where that would not be sufficient?

**Comment by ronandoolan2** [comment]
It would be good to have the option to pass the flag as it is quicker than modifying the kubeconfig.

**Comment by ronandoolan2** [comment]
@julienduchesne can you +2 please?

**Pull request closed without merging**
